Initial attempt at fixing #1805
See sinonjs/sinon#1805

Not functional bundle. Gets this error:

$ node -r esm -e 'import sinon from ./bundle-esm'
file:///home/carlerik/dev/sinon/bundle-esm.js:1
import typeDetect from 'type-detect';

SyntaxError: Missing export 'default' in ES module: file:///home/carlerik/dev/sinon/node_modules/diff/lib/index.js
    at Object.<anonymous> (file:///home/carlerik/dev/sinon/bundle-esm.js:1)