Add proxyquire-universal
This is an attempt at fixing the broken builds in Chrome, that gives us the following error message

  1) sinon module "before each" hook for "should be the fakeServer export from nise":
     TypeError: require.resolve is not a function
      at Object.<anonymous> (node_modules/proxyquire/index.js:6)
      at Object.require.69../lib/proxyquire (null:null)
      at Context.<anonymous> (test/sinon-test.js:15)

See https://travis-ci.org/sinonjs/sinon/jobs/258045216