use JSON.stringify() instead of args.join(", ") to show the expected arguments when using "calledWith" asserts. without this, it returns something like this:
  AssertError: expected method to be called with [Object]

which isn't very helpful.